spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
#tk-Mybatis
mybatis:
  #????????
  type-aliases-package: com.aishang.shop11.po
  mapper-locations: classpath:mapper/*.xml
  # spring boot??mybatis?????sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8082


